-- THIS SCRIPT IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.
DROP TABLE IF EXISTS mimiciv_derived.first_day_bg_art; CREATE TABLE mimiciv_derived.first_day_bg_art AS
/* Highest/lowest blood gas values for arterial blood specimens */
SELECT
  ie.subject_id,
  ie.hadm_id,
  ie.stay_id,
  MIN(lactate) AS lactate_min,
  MAX(lactate) AS lactate_max,
  AVG(lactate) AS lactate_avg,
  MIN(ph) AS ph_min,
  MAX(ph) AS ph_max,
  AVG(ph) AS ph_avg,
  MIN(so2) AS so2_min,
  MAX(so2) AS so2_max,
  AVG(so2) AS so2_avg,
  MIN(po2) AS po2_min,
  MAX(po2) AS po2_max,
  AVG(po2) AS po2_avg,
  MIN(pco2) AS pco2_min,
  MAX(pco2) AS pco2_max,
  AVG(pco2) AS pco2_avg,
  MIN(aado2) AS aado2_min,
  MAX(aado2) AS aado2_max,
  AVG(aado2) AS aado2_avg,
  MIN(aado2_calc) AS aado2_calc_min,
  MAX(aado2_calc) AS aado2_calc_max,
  AVG(aado2_calc) AS aado2_calc_avg,
  MIN(pao2fio2ratio) AS pao2fio2ratio_min,
  MAX(pao2fio2ratio) AS pao2fio2ratio_max,
  AVG(pao2fio2ratio) AS pao2fio2ratio_avg,
  MIN(baseexcess) AS baseexcess_min,
  MAX(baseexcess) AS baseexcess_max,
  AVG(baseexcess) AS baseexcess_avg,
  MIN(bicarbonate) AS bicarbonate_min,
  MAX(bicarbonate) AS bicarbonate_max,
  AVG(bicarbonate) AS bicarbonate_avg,
  MIN(totalco2) AS totalco2_min,
  MAX(totalco2) AS totalco2_max,
  AVG(totalco2) AS totalco2_avg,
  MIN(hematocrit) AS hematocrit_min,
  MAX(hematocrit) AS hematocrit_max,
  AVG(hematocrit) AS hematocrit_avg,
  MIN(hemoglobin) AS hemoglobin_min,
  MAX(hemoglobin) AS hemoglobin_max,
  AVG(hemoglobin) AS hemoglobin_avg,
  MIN(carboxyhemoglobin) AS carboxyhemoglobin_min,
  MAX(carboxyhemoglobin) AS carboxyhemoglobin_max,
  AVG(carboxyhemoglobin) AS carboxyhemoglobin_avg,
  MIN(methemoglobin) AS methemoglobin_min,
  MAX(methemoglobin) AS methemoglobin_max,
  AVG(methemoglobin) AS methemoglobin_avg,
  MIN(temperature) AS temperature_min,
  MAX(temperature) AS temperature_max,
  AVG(temperature) AS temperature_avg,
  MIN(chloride) AS chloride_min,
  MAX(chloride) AS chloride_max,
  AVG(chloride) AS chloride_avg,
  MIN(calcium) AS calcium_min,
  MAX(calcium) AS calcium_max,
  AVG(calcium) AS calcium_avg,
  MIN(glucose) AS glucose_min,
  MAX(glucose) AS glucose_max,
  AVG(glucose) AS glucose_avg,
  MIN(potassium) AS potassium_min,
  MAX(potassium) AS potassium_max,
  AVG(potassium) AS potassium_avg,
  MIN(sodium) AS sodium_min,
  MAX(sodium) AS sodium_max,
  AVG(sodium) AS sodium_avg
FROM mimiciv_icu.icustays AS ie
LEFT JOIN mimiciv_derived.bg AS bg
  ON ie.subject_id = bg.subject_id
  AND bg.specimen = 'ART.'
  AND bg.charttime >= ie.intime - INTERVAL '6 HOUR'
  AND bg.charttime <= ie.intime + INTERVAL '1 DAY'
GROUP BY
  ie.subject_id,
  ie.hadm_id,
  ie.stay_id